services:
  ollama:
    image: ollama/ollama:latest
    container_name: poc_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  chroma:
    image: chromadb/chroma:latest
    container_name: poc_chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE

  app:
    build: .
    container_name: poc_copiloto_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=phi3
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    depends_on:
      - ollama
      - chroma

volumes:
  ollama_data:
  chroma_data:
